version: "3.9"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: totvs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default-network

  pdv-totvs:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db
    networks:
      - default-network

networks:
  default-network:
    driver: bridge
